name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake make g++ gcovr git pkg-config  libcurl4-openssl-dev libasio-dev build-essential python3 ca-certificates

      - name: Make scripts executable
        run: |
          chmod +x ./build.sh ./build_and_run_ut.sh ./run.sh

      - name: Build (Release)
        run: |
          ./build.sh

      - name: Unit tests + coverage
        run: |
          ./build_and_run_ut.sh

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build/report
